name: Update CustomSPM - test

on:
  repository_dispatch:
    types: [update_custom_spm]

jobs:
  update:
    runs-on: macos-latest

    env:
      ACTIONS_RUNNER_DEBUG: "true"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup GitHub Authentication
      run: |
        echo "machine github.com" >> ~/.netrc
        echo "login ${{ secrets.GH_TOKEN }}" >> ~/.netrc
        echo "password x-oauth-basic" >> ~/.netrc
        chmod 600 ~/.netrc  # Ensure the correct permissions

    - name: Clear DerivedData and Cache
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        rm -rf ~/Library/Caches/org.swift.swiftpm/repositories/*

    - name: Checkout main branch
      run: git checkout main

    - name: Update CustomSPM
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        xcodebuild -resolvePackageDependencies -project Example_SPM2.xcodeproj -verbose
        git add .
        git commit -m "Update CustomSPM to latest version"
        git push origin main
