name: Update CustomSPM - test

on:
  repository_dispatch:
    types: [update_custom_spm]

jobs:
  update:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup GitHub Authentication
      run: |
        echo "machine github.com" >> ~/.netrc
        echo "login ${{ secrets.GH_TOKEN }}" >> ~/.netrc
        echo "password x-oauth-basic" >> ~/.netrc

    - name: Checkout main branch
      run: git checkout main

    - name: Update CustomSPM
      run: |
        xcodebuild -resolvePackageDependencies -project Example_SPM2.xcodeproj
        git add .
        git commit -m "Update CustomSPM to latest version"
        git push origin main
