name: Update CustomSPM

on:
  repository_dispatch:
    types: [update_custom_spm]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies -project Example_SPM2.xcodeproj

    - name: Commit and Push Changes
      if: env.dependenciesChanged == 'true'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update CustomSPM to latest version"
        git push origin main
