name: Update CustomSPM

on:
  repository_dispatch:
    types: [update_custom_spm]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout Code
      run:  git checkout main 
